# Generated by Django 5.1 on 2025-11-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_MercadoLibre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=400)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('banco_usuario', models.CharField(max_length=200)),
                ('banco_vendedor', models.CharField(max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('reembolso', 'Reembolso')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.vendedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=20)),
                ('direccion_envio', models.CharField(max_length=400)),
                ('pais_envio', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.vendedor')),
                ('id_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.transaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.vendedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MercadoLibre.usuario')),
            ],
        ),
    ]
