# Generated by Django 5.1 on 2025-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_MercadoLibre', '0002_usuario_transaccion_pedido_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
