# Generated by Django 5.1 on 2025-11-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_MercadoLibre', '0003_pedido_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
    ]
